name: Website static checks

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'
    - run: yarn install
    # --force should be removed if all the issues are fixed
    - run: ./node_modules/.bin/grunt jshint --force
