name: Website Docker Release

on: [ push, pull_request ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: faforever/faf-website
          push: ${{ github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags') }}
          tag_with_ref: true
